// Lista imion męskich - połączenie tradycyjnych imion i najpopularniejszych według GUS
export const maleFirstNames = new Set([
  'ADAM', 'ADRIAN', 'ALAN', 'ALBERT', 'ALEKSANDER', 'ALFRED', 'ALOJZY', 'ANDRZEJ',
  'ANTONI', 'ARTUR', 'BARTŁOMIEJ', 'BARTOSZ', 'BERNARD', 'BŁAŻEJ', 'BOGDAN', 'BOGUSŁAW',
  'BOLESŁAW', 'BORYS', 'BRONISŁAW', 'BRUNO', 'CEZARY', 'CZESŁAW', 'DANIEL', 'DARIUSZ',
  'DAWID', 'DOMINIK', 'EDMUND', 'EDWARD', 'ERYK', 'EUGENIUSZ', 'FABIAN', 'FELIKS',
  'FILIP', 'FRANCISZEK', 'GABRIEL', 'GRZEGORZ', 'GUSTAW', 'HENRYK', 'HUBERT', 'IGNACY',
  'IGOR', 'IRENEUSZ', 'JAN', 'JANUSZ', 'JERZY', 'JÓZEF', 'JULIAN', 'KACPER', 'KAJETAN',
  'KAMIL', 'KAROL', 'KAZIMIERZ', 'KONRAD', 'KORNEL', 'KRYSTIAN', 'KRZYSZTOF', 'KSAWERY',
  'KUBA', 'LEOPOLD', 'LEON', 'LESZEK', 'LUDWIK', 'ŁUKASZ', 'MACIEJ', 'MAKSYMILIAN',
  'MAREK', 'MARIAN', 'MARCIN', 'MARCEL', 'MIECZYSŁAW', 'MIESZKO', 'MIKOŁAJ', 'MILAN',
  'MIŁOSZ', 'NATAN', 'NIKODEM', 'OLAF', 'OLIWIER', 'PATRYK', 'PAWEŁ', 'PIOTR',
  'RAFAŁ', 'ROMAN', 'RYSZARD', 'SEBASTIAN', 'STANISŁAW', 'STEFAN', 'SZCZEPAN',
  'SYLWESTER', 'SZYMON', 'TADEUSZ', 'TEODOR', 'TOMASZ', 'TYMON', 'TYMOTEUSZ',
  'WACŁAW', 'WALDEMAR', 'WIESŁAW', 'WIKTOR', 'WINCENTY', 'WITOLD', 'WŁADYSŁAW',
  'WOJCIECH', 'ZBIGNIEW', 'ZDZISŁAW', 'ZENON', 'ZYGMUNT'
]);

// Lista imion żeńskich - połączenie tradycyjnych imion i najpopularniejszych według GUS
export const femaleFirstNames = new Set([
  'ADA', 'ADELA', 'ADRIANA', 'ADRIANNA', 'AGATA', 'AGNIESZKA', 'ALDONA', 'ALEKSANDRA',
  'ALICJA', 'ALINA', 'AMALIA', 'AMELIA', 'ANASTAZJA', 'ANDŻELIKA', 'ANETA', 'ANGELA',
  'ANGELIKA', 'ANIELA', 'ANITA', 'ANNA', 'ANTONINA', 'APOLONIA', 'AURELIA', 'BARBARA',
  'BEATA', 'BERENIKA', 'BERNADETA', 'BIANKA', 'BLANKA', 'BOGNA', 'BOGUMIŁA', 'BOGUSŁAWA',
  'BOŻENA', 'BRONISŁAWA', 'BRYGIDA', 'CECYLIA', 'CELINA', 'CZESŁAWA', 'DAGMARA', 'DALIA',
  'DANUTA', 'DARIA', 'DIANA', 'DOMINIKA', 'DOROTA', 'EDYTA', 'ELENA', 'ELEONORA',
  'ELIZA', 'ELWIRA', 'ELŻBIETA', 'EMILIA', 'ERNESTYNA', 'ESTERA', 'EUGENIA', 'EWA',
  'EWELINA', 'FAUSTYNA', 'FELICJA', 'FRANCISZKA', 'GABRIELA', 'GAJA', 'GENOWEFA',
  'GRAŻYNA', 'HALINA', 'HANNA', 'HELENA', 'HENRYKA', 'HONORATA', 'IDA', 'IDALIA',
  'IGA', 'ILONA', 'INGA', 'IRENA', 'IWONA', 'IZABELA', 'IZABELLA', 'JADWIGA',
  'JAGODA', 'JAGNA', 'JANINA', 'JAŚMINA', 'JOANNA', 'JOLANTA', 'JOWITA', 'JUDYTA',
  'JULIA', 'JULIANNA', 'JULITA', 'JUSTYNA', 'KAJA', 'KALINA', 'KAMILA', 'KARINA',
  'KAROLINA', 'KATARZYNA', 'KAZIMIERA', 'KINGA', 'KLARA', 'KLAUDIA', 'KONSTANCJA',
  'KORNELIA', 'KRYSTYNA', 'LARA', 'LAURA', 'LEA', 'LENA', 'LEOKADIA', 'LIDIA',
  'LILA', 'LILIA', 'LILIANA', 'LILIANNA', 'LINDA', 'LIWIA', 'LUCYNA', 'LUDMIŁA',
  'LUIZA', 'ŁUCJA', 'MAGDALENA', 'MAJA', 'MALWINA', 'MAŁGORZATA', 'MARCELINA',
  'MARIA', 'MARIANNA', 'MARIOLA', 'MARIKA', 'MARLENA', 'MARTA', 'MARTYNA', 'MARZANNA',
  'MARZENA', 'MATYLDA', 'MAYA', 'MELANIA', 'MIA', 'MICHALINA', 'MILENA', 'MIROSŁAWA',
  'MONIKA', 'NADIA', 'NATALIA', 'NATASZA', 'NEL', 'NELA', 'NICOLA', 'NINA', 'NOEMI',
  'OLIWIA', 'OLGA', 'OLIMPIA', 'OLIVIA', 'OTYLIA', 'PATRYCJA', 'PAULA', 'PAULINA',
  'POLA', 'REGINA', 'RENATA', 'RITA', 'ROKSANA', 'ROMA', 'ROMANA', 'RÓŻA', 'ROZALIA',
  'SABINA', 'SANDRA', 'SARA', 'SOFIA', 'SONIA', 'STANISŁAWA', 'STEFANIA', 'STELLA',
  'SYLWIA', 'TAMARA', 'TATIANA', 'TEKLA', 'TERESA', 'TOLA', 'URSZULA', 'VANESSA',
  'VICTORIA', 'WANDA', 'WERONIKA', 'WIESŁAWA', 'WIKTORIA', 'WIOLETTA', 'WŁADYSŁAWA',
  'ZOJA', 'ZOFIA', 'ZUZANNA', 'ŻANETA'
]);

// Połączona lista wszystkich imion
export const commonFirstNames = new Set([...maleFirstNames, ...femaleFirstNames]);